#ifndef QM_SCREEN_CONFIG_H
#define QM_SCREEN_CONFIG_H

#include "sdkconfig.h"
/*
#ifdef CONFIG_WT154_S2MI1
#define LCD_WR_SCK 12
#define LCD_RS_DC 11
#define LCD_CS 10
#define LCD_RD 13
#define LCD_RST 8
#define LCD_BL 39
#define LCD_D0 35
#define LCD_D1 36
#define LCD_D2 37
#define LCD_D3 38
#define LCD_D4 34
#define LCD_D5 33
#define LCD_D6 21
#define LCD_D7 14
#define SWAP_DATA 0
#define LCD_DRIVER SCREEN_CONTROLLER_ST7789
#define SC_DIR SCR_DIR_LRTB
#elif defined CONFIG_WT_86_32_3ZW0

#define LCD_WR_SCK 39
#define LCD_RS_DC 38
#define LCD_CS -1
#define LCD_RST 37
#define LCD_BL 0
#define LCD_D0 36
#define LCD_D1 35
#define LCD_D2 34
#define LCD_D3 33
#define LCD_D4 21
#define LCD_D5 18
#define LCD_D6 17
#define LCD_D7 16
#define SWAP_DATA 1
#define LCD_DRIVER SCREEN_CONTROLLER_ILI9488
#define SC_DIR SCR_DIR_RLTB

#elif defined CONFIG_WT280_S2MI1
#define LCD_WR_SCK 12
#define LCD_RS_DC 11
#define LCD_CS 10
#define LCD_RST 17
#define LCD_BL 16
#define LCD_D0 35
#define LCD_D1 36
#define LCD_D2 37
#define LCD_D3 34
#define LCD_D4 33
#define LCD_D5 21
#define LCD_D6 14
#define LCD_D7 13
#define SWAP_DATA 1
#define LCD_DRIVER SCREEN_CONTROLLER_ST7789
#define SC_DIR SCR_DIR_LRTB

#elif defined CONFIG_LCD01TG_A_SP
#define LCD_WR_SCK 12
#define LCD_RS_DC 11
#define LCD_CS 10
#define LCD_RST 8
#define LCD_BL 42
#define LCD_RD 15
#define LCD_D0 35
#define LCD_D1 36
#define LCD_D2 37
#define LCD_D3 34
#define LCD_D4 33
#define LCD_D5 21
#define LCD_D6 14
#define LCD_D7 13
#define SWAP_DATA 0
#define LCD_DRIVER SCREEN_CONTROLLER_ILI9341
#define SC_DIR SCR_DIR_TBLR
#endif
*/

#if defined CONFIG_SCR_DIR_LRTB
#define SCR_DIR SCR_DIR_LRTB
#elif defined CONFIG_SCR_DIR_LRBT
#define SCR_DIR SCR_DIR_LRBT
#elif defined CONFIG_SCR_DIR_RLTB
#define SCR_DIR SCR_DIR_RLTB
#elif defined CONFIG_SCR_DIR_RLBT
#define SCR_DIR SCR_DIR_RLBT
#elif defined CONFIG_SCR_DIR_TBLR
#define SCR_DIR SCR_DIR_TBLR
#elif defined CONFIG_SCR_DIR_BTLR
#define SCR_DIR SCR_DIR_BTLR
#elif defined CONFIG_SCR_DIR_TBRL
#define SCR_DIR SCR_DIR_TBRL
#elif defined CONFIG_SCR_DIR_BTRL
#define SCR_DIR SCR_DIR_BTRL
#elif defined CONFIG_SCR_DIR_MAX
#define SCR_DIR SCR_DIR_MAX
#elif defined CONFIG_SCR_MIRROR_X
#define SCR_DIR SCR_MIRROR_X
#elif defined CONFIG_SCR_MIRROR_Y
#define SCR_DIR SCR_MIRROR_Y
#elif defined CONFIG_SCR_SWAP_XY
#define SCR_DIR SCR_SWAP_XY
#else 
#define SCR_DIR -1
#endif

#if defined (CONFIG_CUSTOM_DISPLAY_BUFFER_SIZE)
#define DISP_BUF_SIZE   CONFIG_CUSTOM_DISPLAY_BUFFER_BYTES
#else
#if defined (CONFIG_LV_TFT_DISPLAY_CONTROLLER_ST7789)
#define DISP_BUF_SIZE  (LV_HOR_RES_MAX * 40)
#elif defined CONFIG_LV_TFT_DISPLAY_CONTROLLER_ST7735S
#define DISP_BUF_SIZE  (LV_HOR_RES_MAX * 40)
#elif (defined CONFIG_WT32_SC01_LANDSCAPE)||(defined CONFIG_WT32_SC01_PORTRAIT)
#define DISP_BUF_SIZE  (LV_HOR_RES_MAX * 40)
#elif defined CONFIG_LV_TFT_DISPLAY_CONTROLLER_HX8357
#define DISP_BUF_SIZE  (LV_HOR_RES_MAX * 40)
#elif defined CONFIG_LV_TFT_DISPLAY_CONTROLLER_SH1107
#define DISP_BUF_SIZE  (LV_HOR_RES_MAX * LV_VER_RES_MAX)
#elif defined CONFIG_LV_TFT_DISPLAY_CONTROLLER_ILI9481
#define DISP_BUF_SIZE  (LV_HOR_RES_MAX * 40)
#elif defined CONFIG_LV_TFT_DISPLAY_CONTROLLER_ILI9486
#define DISP_BUF_SIZE  (LV_HOR_RES_MAX * 40)
#elif defined CONFIG_LV_TFT_DISPLAY_CONTROLLER_ILI9488
#define DISP_BUF_SIZE  (LV_HOR_RES_MAX * 40)
#elif defined CONFIG_LV_TFT_DISPLAY_CONTROLLER_ILI9341
#define DISP_BUF_SIZE  (LV_HOR_RES_MAX * 40)
#elif defined CONFIG_LV_TFT_DISPLAY_CONTROLLER_SSD1306
#if defined (CONFIG_LV_THEME_MONO)
#define DISP_BUF_SIZE  (LV_HOR_RES_MAX * (LV_VER_RES_MAX / 8))
#else
#define DISP_BUF_SIZE  (LV_HOR_RES_MAX * LV_VER_RES_MAX)
#endif
#elif defined (CONFIG_LV_TFT_DISPLAY_CONTROLLER_FT81X)
#define DISP_BUF_LINES  40
#define DISP_BUF_SIZE  (LV_HOR_RES_MAX * DISP_BUF_LINES)
#elif defined (CONFIG_LV_TFT_DISPLAY_CONTROLLER_IL3820)
#define DISP_BUF_SIZE (LV_VER_RES_MAX * IL3820_COLUMNS)
#elif defined CONFIG_LV_TFT_DISPLAY_CONTROLLER_RA8875
#define DISP_BUF_SIZE  (LV_HOR_RES_MAX * 40)
#elif defined (CONFIG_LV_TFT_DISPLAY_CONTROLLER_GC9A01)
#define DISP_BUF_SIZE  (LV_HOR_RES_MAX * 40)
#elif defined (CONFIG_LV_TFT_DISPLAY_CONTROLLER_JD79653A)
#define DISP_BUF_SIZE ((LV_VER_RES_MAX * LV_VER_RES_MAX) / 8) // 5KB
#elif defined (CONFIG_LV_TFT_DISPLAY_CONTROLLER_UC8151D)
#define DISP_BUF_SIZE ((LV_VER_RES_MAX * LV_VER_RES_MAX) / 8) // 2888 bytes
#elif defined (CONFIG_WT_SC_8080)
#define DISP_BUF_SIZE 320*40
#else
#define DISP_BUF_SIZE 320*40
#endif
#endif
#if (defined CONFIG_WT_86_32_3ZW0)||(defined CONFIG_WT_86_32_3ZW1)
#ifndef CONFIG_QMSD_PERFORMANCE_MODE
#undef DISP_BUF_SIZE
#define DISP_BUF_SIZE (320 * 320)
#else
#undef DISP_BUF_SIZE
#define DISP_BUF_SIZE (320 * 100)
#endif
#elif defined CONFIG_WT154_S2MI1
#undef DISP_BUF_SIZE
#ifndef CONFIG_QMSD_PERFORMANCE_MODE
#define DISP_BUF_SIZE (240 * 60)
#else
#define DISP_BUF_SIZE (240 * 240)
#endif
#endif
#define SIZE_TO_PIXEL(v) ((v) / sizeof(lv_color_t))
#define PIXEL_TO_SIZE(v) ((v) * sizeof(lv_color_t))
#define BUFFER_NUMBER (1)


#if (defined CONFIG_WT32_SC01_LANDSCAPE)|| (defined CONFIG_WT32_SC01_PORTRAIT)
#define LCD_DRIVER SCREEN_CONTROLLER_ST7796
#elif defined CONFIG_LCD_DRIVER_SCREEN_CONTROLLER_ILI9341
#define LCD_DRIVER SCREEN_CONTROLLER_ILI9341
#elif defined CONFIG_LCD_DRIVER_SCREEN_CONTROLLER_ILI9806
#define LCD_DRIVER SCREEN_CONTROLLER_ILI9806
#elif defined CONFIG_LCD_DRIVER_SCREEN_CONTROLLER_ILI9488
#define LCD_DRIVER SCREEN_CONTROLLER_ILI9488
#elif defined CONFIG_LCD_DRIVER_SCREEN_CONTROLLER_ILI9486
#define LCD_DRIVER SCREEN_CONTROLLER_ILI9486
#elif defined CONFIG_LCD_DRIVER_SCREEN_CONTROLLER_NT35510
#define LCD_DRIVER SCREEN_CONTROLLER_NT35510
#elif defined CONFIG_LCD_DRIVER_SCREEN_CONTROLLER_RM68120
#define LCD_DRIVER SCREEN_CONTROLLER_RM68120
#elif defined CONFIG_LCD_DRIVER_SCREEN_CONTROLLER_ST7789
#define LCD_DRIVER SCREEN_CONTROLLER_ST7789
#elif defined CONFIG_LCD_DRIVER_SCREEN_CONTROLLER_SSD1351
#define LCD_DRIVER SCREEN_CONTROLLER_SSD1351
#else 
#define LCD_DRIVER -1
#endif

#ifdef CONFIG_SCREEN_ROLL_0
#define DIR_INPUT 0
#elif  defined CONFIG_SCREEN_ROLL_1
#define DIR_INPUT 1
#elif  defined CONFIG_SCREEN_ROLL_2
#define DIR_INPUT 2
#elif  defined CONFIG_SCREEN_ROLL_3
#define DIR_INPUT 3
#else
#define DIR_INPUT 0
#endif

#endif