#pragma once

typedef enum {
    QMSD_ERR_OK = 0x00,
    QMSD_ERR_FAIL,
    QMSD_ERR_INVALID_ARG,
    QMSD_ERR_MALLOC_FAIL,
    QMSD_ERR_TIMEOUT,
    QMSD_ERR_LL_NOT_INITED,
    QMSD_ERR_LL_SCREEN_NOT_FOUND,
    QMSD_ERR_LL_ELEMENT_NOT_FOUND,
    QMSD_ERR_LL_ELEMENT_HAS_EXIST,
    QMSD_GUI_CTRL_ERR_NO_ELEMENT,
    QMSD_GUI_CTRL_ERR_TARGET_IS_SCREEN,
    QMSD_ERR_CTRL_ERR_ELEMENT_NOT_FOUND,
    QMSD_ERR_CTRL_ERR_ARGS_WRONG,
    QMSD_GUI_CTRL_ERR_INVALID_INPUT,
    QMSD_GUI_CTRL_ERR_ACTION_NOT_FOUND,
    QMSD_GUI_ERR_FUNC_NOT_SUPPORTED,
} qmsd_err_t;
